name: Setup Gloud
inputs:
  credentials_json:
    required: true
runs:
  using: composite
  steps:
    - name: Setup Gcloud Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ inputs.credentials_json }}"
    - name: Setup Gcloud
      uses: google-github-actions/setup-gcloud@v2
