name: CI
on:
  push:
    branches:
      - "**"

env:
  PROJECT_ID: cut0-blog
  REPOSITORY_NAME: cut0-blog-images
  IMAGE_NAME: cut0-blog

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile

  run_lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint

  run_format:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Format
        run: pnpm format

  run_typecheck:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm typecheck

  push_image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    needs:
      - run_lint
      - run_format
      - run_typecheck
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Setup env
        run: |-
          echo "PUBLIC_GA_ID=${{ secrets.GA_TRACKING_ID }}" >> $GITHUB_ENV
          echo "PUBLIC_END_POINT=${{ secrets.PUBLIC_END_POINT }}" >> $GITHUB_ENV
          echo "PUBLIC_SERVICE_DOMAIN=${{ secrets.PUBLIC_SERVICE_DOMAIN }}" >> $GITHUB_ENV
          echo "PUBLIC_API_KEY=${{ secrets.PUBLIC_API_KEY }}" >> $GITHUB_ENV
      - name: Build App
        run: pnpm build
      - uses: ./.github/actions/setup-gcloud
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
      - name: Setup gcloud for docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
      - name: Setup environment value
        run: |-
          IMAGE="asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_NAME}/${IMAGE_NAME}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
      - name: Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
