name: Deploy Production
on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  purge_firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd ./workspaces/ops
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CUT0_BLOG }}"
          channelId: live
          projectId: cut0-blog
