name: Deploy Production
on:
  workflow_dispatch:
    inputs:
      number:
        description: "Enter a Rollout Version"
        required: true
        default: "1.0.0"

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gcloud
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
      - name: Rollout Version
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cut0-blog
          region: asia-northeast1
          image: "asia-northeast1-docker.pkg.dev/cut0-blog/cut0-blog-images/cut0-blog:${{ github.event.inputs.number }}"
